version: '3.8'

services:
  ml-backend:
    build: ./ml-backend
    ports:
      - "8080:8080"
    volumes:
      - ./ml-backend:/app/ml-backend
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]
    restart: always
